name: 'Test .NET 5.0 Solution'
description: 'This tests a .NET solution that follows specific conventions'
inputs:
  nuget-auth-token:
    description: 'Read-only nuget token, called PACKAGE_READ_GITHUB_TOKEN in Arundo'
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Install .NET 5.0 latest
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        source-url: https://nuget.pkg.github.com/arundo/index.json
      env:
        NUGET_AUTH_TOKEN: ${{inputs.nuget-auth-token}}
    
    - name: Test and save test results
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
      shell: bash

    - name: Send Test results to Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{inputs.nuget-auth-token}}
#        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./tests/UnitTests/TestResults/coverage.info
